# -*- coding: utf-8 -*-
"""viva_project_groq

Automatically generated by Colab.


"""

# ==============================================================================
# ⚙️ EXAMINER VIVA CONFIGURATIONS
# ------------------------------------------------------------------------------
# Faculty-specific settings (subject, difficulty, time limit, question count)
# now live in the separate viva_config.py file next to this script — that is
# the ONLY file another faculty member needs to edit to reuse this app for
# their own subject. See viva_config.py for instructions. The try/except
# below just keeps this script working with sensible defaults if that file
# is ever missing.
# ==============================================================================
try:
    from viva_config import (
        VIVA_SUBJECT,
        VIVA_DIFFICULTY,
        VIVA_TOTAL_QUESTIONS,
        VIVA_TIME_LIMIT_MINUTES,
        AVAILABLE_SUBJECTS,
        VIVA_CUSTOM_INSTRUCTIONS,
        VIVA_MANDATORY_QUESTIONS,
    )
except ImportError:
    VIVA_SUBJECT = "Organizational Behaviour"
    VIVA_DIFFICULTY = "Standard"
    VIVA_TOTAL_QUESTIONS = 10
    VIVA_TIME_LIMIT_MINUTES = 10
    AVAILABLE_SUBJECTS = [
        "Marketing Management",
        "Financial Management",
        "Human Resource Management",
        "Organizational Behaviour",
        "Organizational Behaviour 2",
        "Business Strategy",
    ]
    VIVA_CUSTOM_INSTRUCTIONS = ""
    VIVA_MANDATORY_QUESTIONS = []
# ==============================================================================

import streamlit as st
import streamlit.components.v1 as components
from google import genai
from google.genai import types as genai_types
import fitz
from docx import Document
import io
import re
import time
from datetime import datetime
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import os
import requests
import json
import random
import uuid
from filelock import FileLock, Timeout as FileLockTimeout

st.set_page_config(page_title="GLIM Project Viva Examiner", page_icon="🎓")
st.title("🎓 GLIM Project Viva Examiner")
st.caption("Powered by Google Gemini (your own free API key) — 📝 Text-Based Viva Mode")

# Save the scoresheet in the SAME folder as this script, regardless of where
# Streamlit is launched from. This makes it easy to find on disk.
try:
    _SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    # __file__ isn't defined in some interactive contexts (e.g. Jupyter); fall back to cwd
    _SCRIPT_DIR = os.getcwd()
SCORESHEET_FILE = os.path.join(_SCRIPT_DIR, "GLIM_Viva_Scores.xlsx")
# Every student's session shares this ONE file. Without a lock, two students
# finishing at nearly the same moment can both load the workbook, append
# their row in memory, and save — the second save silently overwrites the
# first (lost row), or a save landing mid-read produces a corrupted
# .xlsx that fails to open for every student after that. The lock file
# below serializes access so saves queue up safely instead of colliding.
SCORESHEET_LOCK = SCORESHEET_FILE + ".lock"

# Component directory for the dynamic timer and cheat monitor.
#
# IMPORTANT: this must be UNIQUE PER STUDENT SESSION, not one shared folder.
# render_viva_controller() rewrites index.html on every rerun with THAT
# session's remaining_seconds, then serves it via declare_component(). If
# every session pointed at the same folder/name (as this used to), two
# students answering around the same moment could each load the OTHER's
# countdown, or catch the file mid-write and get a broken/blank timer and
# anti-cheat panel. A per-session id keeps every student's file (and the
# component's internal registration) fully isolated from every other
# student's, while still being reused across that one student's own reruns.
if "component_session_id" not in st.session_state:
    st.session_state.component_session_id = uuid.uuid4().hex
COMPONENT_SESSION_ID = st.session_state.component_session_id
COMPONENT_DIR = os.path.join(_SCRIPT_DIR, "viva_controller_component", COMPONENT_SESSION_ID)
# exist_ok=True avoids a FileExistsError race: on Streamlit Cloud, two
# students' sessions can both hit this startup code within the same
# instant, and one can create the folder in the gap between the other's
# os.path.exists() check and its os.makedirs() call.
os.makedirs(COMPONENT_DIR, exist_ok=True)

# --- Dynamic HTML/JS Controller Component ---
def render_viva_controller(remaining_seconds):
    html_code = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        .timer-box {{
            font-family: 'Arial', sans-serif;
            background: #ffebee; color: #c62828;
            padding: 12px; border-radius: 8px; border: 1px solid #ffcdd2;
            text-align: center; margin-bottom: 15px; font-weight: bold;
        }}
        .timer-label {{
            font-size: 10px; text-transform: uppercase; letter-spacing: 1px;
            color: #b71c1c; margin-bottom: 4px;
        }}
        .timer-value {{ font-size: 22px; }}
        .fs-box {{
            font-family: 'Arial', sans-serif; background: #fff8e1;
            border: 1px solid #ffe082; border-radius: 8px; padding: 10px;
            text-align: center; margin-bottom: 15px;
        }}
        .fs-warn {{ font-size: 11px; color: #e65100; margin-bottom: 6px; }}
        .fs-btn {{
            background: #e65100; color: #fff; border: none; border-radius: 6px;
            padding: 8px 14px; font-weight: bold; font-size: 13px;
            cursor: pointer; width: 100%;
        }}
    </style>
    <script>
    // ---- Streamlit component handshake (REQUIRED) -------------------------
    function _post(type, data) {{
        window.parent.postMessage(Object.assign({{isStreamlitMessage: true, type: type}}, data), "*");
    }}
    function sendValue(value) {{
        _post("streamlit:setComponentValue", {{value: value, dataType: "json"}});
    }}
    _post("streamlit:componentReady", {{apiVersion: 1}});
    _post("streamlit:setFrameHeight", {{height: 150}});

    let timeLeft = {remaining_seconds};
    function updateTimerDisplay() {{
        let m = Math.floor(timeLeft / 60);
        let s = timeLeft % 60;
        if (s < 10) s = "0" + s;
        let el = document.getElementById("timer");
        if (el) el.innerText = m + ":" + s;
        if (timeLeft < 60) {{
            let c = document.getElementById("timer-container");
            if (c) c.style.background = "#ffcdd2";
        }}
    }}
    let timerInterval = setInterval(function() {{
        timeLeft--;
        if (timeLeft <= 0) {{ clearInterval(timerInterval); sendValue("timeout"); }}
        else {{ updateTimerDisplay(); }}
    }}, 1000);

    // ---- ANTI-CHEAT / EXAM LOCK-DOWN -------------------------------------
    let cheatReported = false;
    function reportCheat(reason) {{
        if (cheatReported) return;
        cheatReported = true;
        try {{ console.warn("VIVA cheat trigger: " + reason); }} catch (e) {{}}
        sendValue("cheated");
    }}
    let guardWin, guardDoc;
    try {{ guardWin = window.top; guardDoc = window.top.document; void guardDoc.visibilityState; }}
    catch (e) {{ guardWin = window; guardDoc = document; }}
    document.addEventListener('visibilitychange', function() {{
        if (document.visibilityState === 'hidden') reportCheat("tab hidden / minimized");
    }});
    try {{
        guardDoc.addEventListener('visibilitychange', function() {{
            if (guardDoc.visibilityState === 'hidden') reportCheat("tab hidden (top)");
        }});
    }} catch (e) {{}}
    window.addEventListener('blur', function() {{ reportCheat("focus lost / another window opened"); }});
    try {{ guardWin.addEventListener('blur', function() {{ reportCheat("focus lost (top)"); }}); }} catch (e) {{}}
    try {{
        guardDoc.addEventListener('contextmenu', function(e) {{ e.preventDefault(); }});
        ['copy','cut','paste'].forEach(function(ev) {{
            guardDoc.addEventListener(ev, function(e) {{ e.preventDefault(); }});
        }});
    }} catch (e) {{}}
    function keyGuard(e) {{
        let k = (e.key || "").toLowerCase();
        let cmd = e.ctrlKey || e.metaKey;
        if (cmd && ['t','n','w','tab'].indexOf(k) !== -1) {{
            e.preventDefault(); reportCheat("blocked new-window/tab shortcut: " + k);
        }}
        if (k === 'f12' || (cmd && e.shiftKey && ['i','j','c'].indexOf(k) !== -1) || (cmd && k === 'u')) {{
            e.preventDefault(); reportCheat("blocked dev-tools / view-source");
        }}
    }}
    window.addEventListener('keydown', keyGuard, true);
    try {{ guardWin.addEventListener('keydown', keyGuard, true); }} catch (e) {{}}
    try {{ guardWin.addEventListener('beforeunload', function(e) {{ e.preventDefault(); e.returnValue = ""; }}); }} catch (e) {{}}
    function isFullscreen() {{
        try {{ return !!(guardDoc.fullscreenElement || guardDoc.webkitFullscreenElement); }}
        catch (e) {{ return !!(document.fullscreenElement); }}
    }}
    function syncFullscreenUI() {{
        let box = document.getElementById("fs-box");
        if (box) box.style.display = isFullscreen() ? "none" : "block";
    }}
    function enterFullscreen() {{
        try {{
            let el = guardDoc.documentElement;
            let req = el.requestFullscreen || el.webkitRequestFullscreen;
            if (req) {{ req.call(el); try {{ guardWin.__vivaFS = true; }} catch (e) {{}} }}
        }} catch (e) {{}}
    }}
    function fsChange() {{
        let entered = false;
        try {{ entered = !!guardWin.__vivaFS; }} catch (e) {{}}
        if (!isFullscreen() && entered) reportCheat("exited fullscreen during exam");
        syncFullscreenUI();
    }}
    try {{ guardDoc.addEventListener('fullscreenchange', fsChange); }} catch (e) {{}}
    document.addEventListener('fullscreenchange', fsChange);
    window.addEventListener("load", function() {{
        updateTimerDisplay();
        let btn = document.getElementById("fs-btn");
        if (btn) btn.addEventListener("click", enterFullscreen);
        syncFullscreenUI();
    }});
    </script>
</head>
<body style="margin:0; padding:0; background:transparent;">
    <div id="fs-box" class="fs-box" style="display:none;">
        <div class="fs-warn">WARNING: This viva must run in fullscreen.<br>Exiting fullscreen will submit your exam.</div>
        <button id="fs-btn" class="fs-btn">Enter Fullscreen to continue</button>
    </div>
    <div id="timer-container" class="timer-box">
        <div class="timer-label">Time Remaining</div>
        <div id="timer" class="timer-value">--:--</div>
    </div>
</body>
</html>
"""
    with open(os.path.join(COMPONENT_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(html_code)

    focus_monitor = components.declare_component(
        f"viva_controller_{COMPONENT_SESSION_ID}", path=COMPONENT_DIR
    )
    return focus_monitor(key="viva_control_instance")

# --- Gemini model candidates ---
# Each student brings their OWN free Gemini API key (entered in the sidebar)
# instead of everyone sharing one faculty-managed key, so one student's
# usage can no longer rate-limit or block anyone else's viva.
#
# Google renames/retires model IDs often — an earlier version of this list
# (gemini-2.5-flash / gemini-2.0-flash / gemini-2.5-flash-lite) went 404 on
# a real key because Google had moved past that generation entirely. These
# are simply a fast-path first guess, checked against the live model
# lineup as of when this was last updated; chat_with_llm() below does NOT
# depend on this list being right — if every entry here 404s, it asks the
# API directly (client.models.list()) what THIS key can actually reach and
# uses that instead, so a future rename can't break the app the same way
# again. Update this list opportunistically, but it's a convenience, not a
# requirement.
GEMINI_MODEL_CANDIDATES = [
    "gemini-3.5-flash-lite",
    "gemini-3.6-flash",
    "gemini-3.1-flash-lite",
    "gemini-2.5-flash",
]

def _discover_gemini_models(client):
    """Last-resort fallback used only when every GEMINI_MODEL_CANDIDATES
    entry 404s: asks the Gemini API directly which models THIS key can
    reach and use for generateContent, instead of us guessing a name from
    outside documentation that may already be stale. Prefers lighter/
    cheaper "flash"-family, "lite" models — faster and with more generous
    free-tier limits — over "pro" or other heavier ones."""
    try:
        models = list(client.models.list())
    except Exception:
        return []
    names = []
    for m in models:
        actions = getattr(m, "supported_actions", None) or []
        if actions and "generateContent" not in actions:
            continue
        name = (getattr(m, "name", None) or "").split("/")[-1]
        if name:
            names.append(name)

    def sort_key(n):
        n_low = n.lower()
        return (
            0 if "flash" in n_low else (1 if "pro" in n_low else 2),
            0 if "lite" in n_low else 1,
            len(n),
        )
    names.sort(key=sort_key)
    return names

def _to_gemini_contents(messages):
    """Converts our internal OpenAI-style [{"role", "content"}, ...] history
    into Gemini's shape: a separate system_instruction string, plus a
    contents list of genai_types.Content (role "user" or "model")."""
    system_instruction = None
    contents = []
    for m in messages:
        if m["role"] == "system":
            # Only one system message exists in this app; if that ever
            # changes, later ones would overwrite earlier ones here.
            system_instruction = m["content"]
        else:
            role = "model" if m["role"] == "assistant" else "user"
            contents.append(genai_types.Content(
                role=role, parts=[genai_types.Part.from_text(text=m["content"])]
            ))

    if not contents:
        # The very first call of a viva has ONLY the system message so far
        # (the opening greeting hasn't been generated yet) — unlike Groq/
        # OpenAI-style chat APIs, Gemini rejects an empty `contents` list
        # outright ("contents are required"), so give it a minimal kickoff
        # turn. The system prompt already ends with an explicit instruction
        # to begin by greeting the student, so this just triggers that.
        contents.append(genai_types.Content(
            role="user", parts=[genai_types.Part.from_text(text="Begin the viva now.")]
        ))
    return system_instruction, contents

def chat_with_llm(messages, max_retries=5):
    """Calls the Gemini API with the CURRENT STUDENT'S OWN key, retrying
    transient/rate-limit errors with backoff and falling back through
    GEMINI_MODEL_CANDIDATES — and, if every one of those 404s, through a
    live discovery of whatever models this key can actually reach — on a
    "model not found" response. Only gives up (with a friendly message,
    plus the real error for troubleshooting) once every avenue is
    exhausted.
    """
    api_key = (st.session_state.get("gemini_api_key") or "").strip()
    if not api_key:
        st.error("⚠️ Enter your Gemini API key in the sidebar before starting the viva.")
        return None

    client = genai.Client(api_key=api_key)
    system_instruction, contents = _to_gemini_contents(messages)
    config = genai_types.GenerateContentConfig(
        system_instruction=system_instruction,
        max_output_tokens=1024,
        temperature=0.4,
    )
    last_error = None

    def try_models(model_list):
        """Tries each model in model_list in turn. Returns ("success", text),
        ("not_found", None) if every one 404'd, or ("terminal", None) if an
        error message was already shown to the user (nothing more to try)."""
        nonlocal last_error
        for model_name in model_list:
            for attempt in range(max_retries):
                try:
                    response = client.models.generate_content(
                        model=model_name, contents=contents, config=config,
                    )
                    st.session_state.gemini_working_model = model_name
                    return "success", response.text
                except Exception as e:
                    last_error = e
                    msg = str(e).lower()

                    if any(tok in msg for tok in
                           ["api key not valid", "api_key_invalid", "permission_denied",
                            "401", "403"]):
                        st.error(
                            "⚠️ Your Gemini API key was rejected. Double-check you pasted "
                            "it correctly, or get a fresh free key at "
                            "https://aistudio.google.com/apikey."
                        )
                        return "terminal", None

                    if any(tok in msg for tok in ["404", "not found", "does not exist"]):
                        # This model isn't reachable on this key — try the
                        # next candidate instead of burning retries here.
                        break

                    if any(tok in msg for tok in
                           ["400", "invalid_argument", "invalid argument"]):
                        # A malformed request (e.g. once, an empty `contents`
                        # list on the very first call). Retrying won't help —
                        # the exact same request would just fail the exact
                        # same way — so say so plainly instead of the
                        # misleading "temporarily busy" message, which would
                        # send a student into a pointless retry loop.
                        st.error(
                            "⚠️ The examiner AI rejected this request as malformed — "
                            "this points to a bug in the app rather than something "
                            "retrying will fix. Please tell your faculty, including "
                            "the technical details below."
                        )
                        with st.expander("Technical details (for troubleshooting)"):
                            st.code(str(last_error))
                        return "terminal", None

                    is_transient = any(tok in msg for tok in
                                        ["429", "resource_exhausted", "rate limit", "quota",
                                         "timeout", "timed out", "502", "503", "unavailable",
                                         "connection"])
                    if is_transient and attempt < max_retries - 1:
                        wait = (2 ** attempt) + random.uniform(0, 1)
                        time.sleep(wait)
                        continue

                    # A non-transient, non-404 error, or retries exhausted on
                    # a transient one: give up rather than silently cycling
                    # every remaining candidate model.
                    st.error(
                        "⚠️ The examiner AI is temporarily busy or rate-limited. "
                        "Please wait a few seconds, then submit your answer "
                        "again — nothing has been lost."
                    )
                    with st.expander("Technical details (for troubleshooting)"):
                        st.code(str(last_error))
                    return "terminal", None
        return "not_found", None

    # Once we've found a model THIS key can reach, keep using it for the
    # rest of the viva instead of re-probing every candidate on every call.
    first_pass = (
        [st.session_state["gemini_working_model"]]
        if st.session_state.get("gemini_working_model")
        else GEMINI_MODEL_CANDIDATES
    )
    outcome, text = try_models(first_pass)
    if outcome == "success":
        return text
    if outcome == "terminal":
        return None

    # Every hardcoded candidate 404'd — ask the API directly what this key
    # can actually reach instead of guessing another name from outside.
    discovered = [m for m in _discover_gemini_models(client) if m not in first_pass]
    if discovered:
        outcome, text = try_models(discovered)
        if outcome == "success":
            return text
        if outcome == "terminal":
            return None

    st.error(
        "⚠️ No usable Gemini model could be found for your API key — neither "
        f"the expected ones ({', '.join(GEMINI_MODEL_CANDIDATES)}) nor anything "
        "discovered by asking the API directly. Check "
        "https://aistudio.google.com/ while signed into the Google account "
        "the key belongs to, and confirm the Generative Language API is "
        "enabled for it."
    )
    with st.expander("Technical details (for troubleshooting)"):
        st.code(str(last_error))
    return None

# --- Save to Google Sheets via Webhook ---
def save_to_google_sheets(student_name, student_roll, student_email, subject, difficulty, score,
                          grade, strengths, improvements, exchanges, project_name):
    """Posts one row to the Google Sheet webhook. Returns (success, message)
    instead of calling st.error/st.warning directly — those calls only ever
    render on the ONE script rerun where this function happens to execute;
    on every later rerun of the same "viva ended" screen, Streamlit doesn't
    replay them, so a real error can flash for a moment and then vanish
    before anyone reads it. The caller stores the returned message in
    st.session_state and re-displays it on every rerun instead, so a
    misconfiguration is actually visible rather than silently disappearing.
    """
    webhook_url = st.secrets.get("GSHEETS_WEBHOOK_URL") or os.environ.get("GSHEETS_WEBHOOK_URL")
    if not webhook_url:
        return False, (
            "Google Sheets NOT saved: the GSHEETS_WEBHOOK_URL secret is missing or empty. "
            "In Streamlit -> Settings -> Secrets add a line exactly like:  "
            'GSHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/XXX/exec"  '
            "then Save and Reboot."
        )
    if not str(webhook_url).strip().endswith("/exec"):
        return False, (
            "Your GSHEETS_WEBHOOK_URL does not end in /exec. Use the Apps Script Web App "
            "URL from Deploy -> Web app, not the editor or /dev URL."
        )

    payload = {
        "student_name": student_name,
        "student_roll": student_roll,
        "student_email": student_email,
        "subject": subject,
        "difficulty": difficulty,
        "project_name": project_name,
        "score": score,
        "grade": grade,
        "exchanges": exchanges,
        "strengths": strengths,
        "improvements": improvements
    }

    try:
        response = requests.post(webhook_url, json=payload, timeout=15)
        if response.status_code == 200 and "Success" in response.text:
            return True, "📊 Score successfully posted to Google Sheets!"
        else:
            return False, (
                "Google Sheets did not accept the data (HTTP "
                + str(response.status_code) + "). Response start: "
                + str(response.text)[:300]
                + "  ->  Most likely the Apps Script Web App access is not set to "
                "'Anyone', or you edited the script without deploying a NEW version."
            )
    except Exception as e:
        return False, f"⚠️ Failed to write to Google Sheets: {e}"

# --- Extract text from uploaded file ---
def extract_text(uploaded_file):
    text = ""
    if uploaded_file.name.endswith(".pdf"):
        pdf_bytes = uploaded_file.read()
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        for page in doc:
            text += page.get_text()
    elif uploaded_file.name.endswith(".docx"):
        doc = Document(io.BytesIO(uploaded_file.read()))
        for para in doc.paragraphs:
            text += para.text + "\n"
    return text.strip()

def truncate(text, max_chars=6000):
    if len(text) > max_chars:
        return text[:max_chars] + "\n\n[... project continues ...]"
    return text

# --- Scoring scale (top-level constant so it's the ONE place to change the
#     scale if it's ever adjusted again) ---
VIVA_MAX_SCORE = 15

# --- Parse score from closing message ---
def parse_score(text):
    """Try a series of regex patterns to pull a 0-VIVA_MAX_SCORE score out of
    the LLM reply. The patterns are tried in order — most specific first."""
    if not text:
        return None
    # Strip markdown emphasis (*, **) so they don't trip up the regex
    cleaned = re.sub(r'[\*_`]', '', text)

    m = VIVA_MAX_SCORE
    patterns = [
        # "Score: 11/15" or "Score - 11.5 / 15"
        rf'score\s*[:\-]?\s*(\d+(?:\.\d+)?)\s*/\s*{m}',
        # "Final score: 11" or "Overall score 11.5"
        r'(?:final|overall)?\s*score\s*[:\-]?\s*(\d+(?:\.\d+)?)\b',
        # "11/15" or "11.5 / 15" anywhere in the text
        rf'\b(\d+(?:\.\d+)?)\s*/\s*{m}\b',
        # "11 out of 15"
        rf'\b(\d+(?:\.\d+)?)\s+out\s+of\s+{m}\b',
        # "I would give this an 11"
        rf'(?:give|rate|award)\s+(?:this|you|the\s+student)?\s*(?:an?\s+)?(\d+(?:\.\d+)?)\s*(?:/\s*{m})?',
    ]
    for pattern in patterns:
        match = re.search(pattern, cleaned, re.IGNORECASE)
        if match:
            try:
                value = float(match.group(1))
                # sanity check: must be a plausible 0-VIVA_MAX_SCORE mark
                if 0 <= value <= VIVA_MAX_SCORE:
                    return value
            except ValueError:
                continue
    return None

# --- Parse strengths and improvements ---
def parse_feedback(text):
    strengths, improvements = "", ""
    s = re.search(
        r'strength[s]?[:\-\*\s]+(.*?)(?=area|improvement|weakness|recommend|$)',
        text, re.IGNORECASE | re.DOTALL)
    if s:
        strengths = s.group(1).strip()[:300]
    i = re.search(
        r'(?:area[s]? (?:for|needing)|improvement[s]?|weakness)[:\-\*\s]+(.*?)(?=recommend|suggest|$)',
        text, re.IGNORECASE | re.DOTALL)
    if i:
        improvements = i.group(1).strip()[:300]
    return strengths, improvements

# --- Save to Excel ---
def save_to_excel(student_name, student_roll, student_email, subject, difficulty, score,
                  grade, strengths, improvements, exchanges, project_name, row_num=None):
    """Write one student's result to the local scoresheet.

    row_num=None (the normal case) appends a new row and returns
    (filepath, the_row_number_written). Pass that returned row number back
    in as row_num on a later call (e.g. when a manual score override
    re-saves the same student) to overwrite that same row in place instead
    of appending a second, duplicate row for the same viva."""

    thin = Side(style='thin')
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    header_font = Font(name='Arial', bold=True, color='FFFFFF', size=11)
    header_fill = PatternFill('solid', start_color='1F4E79')
    center = Alignment(horizontal='center', vertical='center', wrap_text=True)
    left = Alignment(horizontal='left', vertical='center', wrap_text=True)

    if score is None:
        score_fill = PatternFill('solid', start_color='D9D9D9')
    elif score >= 12:   # 8/10 equivalent
        score_fill = PatternFill('solid', start_color='C6EFCE')
    elif score >= 9:    # 6/10 equivalent
        score_fill = PatternFill('solid', start_color='FFEB9C')
    else:
        score_fill = PatternFill('solid', start_color='FFC7CE')

    with FileLock(SCORESHEET_LOCK, timeout=30):
        written_row = _write_excel_row(student_name, student_roll, student_email, subject, difficulty, score, grade,
                          strengths, improvements, exchanges, project_name,
                          thin, border, header_font, header_fill, center,
                          left, score_fill, row_num=row_num)
    return SCORESHEET_FILE, written_row

def _ensure_column(ws, position, header, header_font, header_fill, center, border, width):
    """Insert `header` as a new column at `position` if a sheet saved before
    that column existed doesn't have it yet. Callers must ensure columns in
    left-to-right order so each insertion doesn't shift a column already
    ensured back out of place."""
    if ws.cell(row=1, column=position).value != header:
        ws.insert_cols(position)
        cell = ws.cell(row=1, column=position, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border
        ws.column_dimensions[get_column_letter(position)].width = width

def _write_excel_row(student_name, student_roll, student_email, subject, difficulty, score, grade,
                      strengths, improvements, exchanges, project_name,
                      thin, border, header_font, header_fill, center,
                      left, score_fill, row_num=None):
    """The actual read-modify-write, called only while SCORESHEET_LOCK is held.
    Returns the row number written to."""
    if os.path.exists(SCORESHEET_FILE):
        wb = load_workbook(SCORESHEET_FILE)
        ws = wb.active

        # One-time migration for sheets saved before Roll No / Email existed
        # as columns, so old rows and new rows stay aligned under the same
        # headers instead of every later column being off by one or two.
        _ensure_column(ws, 4, "Roll No", header_font, header_fill, center, border, 16)
        _ensure_column(ws, 5, "Email", header_font, header_fill, center, border, 26)

        # A previous save appends a "Total Students" summary block a couple of
        # rows below the last student. Always strip it before writing (both
        # on a plain append AND on an in-place overwrite below) so we never
        # leave a stale summary row scattered through the data, and so the
        # summary gets freshly recomputed against the current last row.
        for r in range(ws.max_row, 1, -1):
            if ws.cell(row=r, column=1).value == "Total Students":
                ws.delete_rows(r, ws.max_row - r + 1)
                break

        # row_num set (and pointing at a real data row for this same student)
        # means this is a re-save of an already-written row — e.g. applying a
        # manual score after the examiner failed to return one — so overwrite
        # that row in place instead of appending a duplicate one below it.
        if (row_num is not None and 2 <= row_num <= ws.max_row
                and str(ws.cell(row=row_num, column=4).value or "").strip() == str(student_roll or "").strip()):
            next_row = row_num
        else:
            next_row = ws.max_row + 1
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = "Viva Scores"

        headers = ["S.No", "Date", "Student Name", "Roll No", "Email", "Subject",
                   "Difficulty", "Project File", "Score (/15)",
                   "Grade", "Exchanges", "Strengths", "Areas for Improvement"]
        col_widths = [6, 18, 20, 16, 26, 22, 12, 28, 12, 20, 10, 40, 40]

        for col, (h, w) in enumerate(zip(headers, col_widths), 1):
            cell = ws.cell(row=1, column=col, value=h)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = center
            cell.border = border
            ws.column_dimensions[get_column_letter(col)].width = w

        ws.row_dimensions[1].height = 30
        ws.freeze_panes = "A2"
        next_row = 2

    row_data = [
        next_row - 1,
        datetime.now().strftime("%d-%b-%Y %H:%M"),
        student_name or "Unknown",
        student_roll or "—",
        student_email or "—",
        subject,
        difficulty,
        project_name,
        score if score is not None else "Pending",
        grade,
        exchanges,
        strengths or "—",
        improvements or "—"
    ]

    for col, value in enumerate(row_data, 1):
        cell = ws.cell(row=next_row, column=col, value=value)
        cell.font = Font(name='Arial', size=10)
        cell.border = border
        cell.alignment = center if col in [1, 9, 10, 11] else left
        if col == 9:
            cell.fill = score_fill
            cell.font = Font(name='Arial', size=10, bold=True)
        elif next_row % 2 == 0:
            cell.fill = PatternFill('solid', start_color='EBF3FB')

    ws.row_dimensions[next_row].height = 40

    # Summary row — placed after the true last data row, which is normally
    # next_row but could be a later row if an in-place overwrite targeted a
    # row above the current last one.
    last_data_row = max(next_row, ws.max_row)
    summary_row = last_data_row + 2
    for col, (label, formula) in enumerate([
        ("Total Students", f'=COUNTA(C2:C{last_data_row})'),
        ("Avg Score", f'=IFERROR(AVERAGEIF(I2:I{last_data_row},"<>Pending",I2:I{last_data_row}),"-")'),
        ("Highest", f'=IFERROR(MAX(I2:I{last_data_row}),"-")'),
        ("Lowest", f'=IFERROR(MINIFS(I2:I{last_data_row},I2:I{last_data_row},"<>Pending"),"-")')
    ], start=1):
        label_cell = ws.cell(row=summary_row, column=col*2-1, value=label)
        label_cell.font = Font(name='Arial', bold=True, color='FFFFFF', size=10)
        label_cell.fill = PatternFill('solid', start_color='2E75B6')
        label_cell.alignment = center

        val_cell = ws.cell(row=summary_row, column=col*2, value=formula)
        val_cell.font = Font(name='Arial', bold=True, size=10)
        val_cell.alignment = center

    wb.save(SCORESHEET_FILE)
    return next_row

# --- Prevent a student from re-attempting the viva with the same link ---
def get_local_completed_rolls():
    """Returns the set of normalized Roll Numbers that already have a viva
    recorded in the LOCAL scoresheet on this running app instance. This
    resets if Streamlit Cloud restarts the app (a redeploy, or the container
    recycling after long inactivity) — kept only as an extra safety net
    alongside the durable Google Sheet check below.
    """
    if not os.path.exists(SCORESHEET_FILE):
        return set()
    try:
        with FileLock(SCORESHEET_LOCK, timeout=15):
            wb = load_workbook(SCORESHEET_FILE, read_only=True)
            ws = wb.active
            header_row = next(ws.iter_rows(min_row=1, max_row=1, values_only=True), ())
            if "Roll No" not in header_row:
                return set()
            roll_col = header_row.index("Roll No")
            rolls = set()
            for row in ws.iter_rows(min_row=2, values_only=True):
                value = row[roll_col] if roll_col < len(row) else None
                if value and str(value).strip():
                    rolls.add(str(value).strip().lower())
            return rolls
    except Exception:
        # Fail OPEN: an unreadable/locked scoresheet shouldn't itself block
        # a legitimate student from starting. Worst case here is a rare
        # missed duplicate, not the whole class getting locked out.
        return set()

@st.cache_data(ttl=20, show_spinner=False)
def get_remote_completed_rolls():
    """Reads the DURABLE list of Roll Numbers already recorded in the Google
    Sheet (via a GET request to the same Apps Script Web App the score
    webhook already posts to). Unlike the local file, this survives an app
    restart, so it's the authoritative check. Cached for a short window
    (20s) so every student's page render doesn't hit the Apps Script quota —
    a student who just finished may take up to ~20s to show up as blocked
    for someone else reloading the link, which is an acceptable trade-off.
    """
    webhook_url = st.secrets.get("GSHEETS_WEBHOOK_URL") or os.environ.get("GSHEETS_WEBHOOK_URL")
    if not webhook_url:
        return set()
    try:
        response = requests.get(webhook_url, timeout=10)
        data = response.json()
        return {str(r).strip().lower() for r in data.get("rolls", []) if r is not None and str(r).strip()}
    except Exception:
        # Fail OPEN here too: a network hiccup or a Sheet script that hasn't
        # been updated with the doGet handler yet shouldn't block students —
        # the local check below still catches same-session repeats.
        return set()

def get_completed_rolls():
    """Union of the durable Google Sheet record and the local scoresheet —
    a student is blocked if EITHER source already shows a completed viva
    for their Roll Number."""
    return get_local_completed_rolls() | get_remote_completed_rolls()

# --- Grade helper ---
# Thresholds are the old /10 cutoffs (9, 8, 7, 6, 5) scaled up by 1.5x to the
# /15 scale, so the same proportion of the scale earns each grade as before.
def get_grade(score):
    if score is None:
        return "N/A"
    elif score >= 13.5:
        return "O (Outstanding)"
    elif score >= 12:
        return "A+ (Excellent)"
    elif score >= 10.5:
        return "A (Very Good)"
    elif score >= 9:
        return "B (Good)"
    elif score >= 7.5:
        return "C (Average)"
    else:
        return "F (Fail)"

# --- Sidebar ---
with st.sidebar:
    st.header("⚙️ Viva Settings")
    
    # Subject selection or lock
    if VIVA_SUBJECT:
        subject = st.text_input("Subject (Locked)", value=VIVA_SUBJECT, disabled=True)
    else:
        subject = st.selectbox("Subject", AVAILABLE_SUBJECTS)
        
    # Difficulty selection or lock
    if VIVA_DIFFICULTY:
        difficulty = st.text_input("Difficulty (Locked)", value=VIVA_DIFFICULTY, disabled=True)
    else:
        difficulty = st.selectbox("Difficulty", ["Easy", "Standard", "Rigorous"])
        
    student_name = st.text_input("Student Name", placeholder="Enter full name...")
    student_roll = st.text_input("Student Roll", placeholder="Enter roll number...")
    student_email = st.text_input("Student Email", placeholder="Enter email address...")
    if student_email and "@" not in student_email:
        st.warning("That doesn't look like a valid email address.")

    # Block a repeat attempt with the same Roll Number on this same link.
    # Roll Number is now required (not just Name) precisely because it's
    # the key this check relies on.
    normalized_roll = (student_roll or "").strip().lower()
    already_done = bool(normalized_roll) and normalized_roll in get_completed_rolls()
    if already_done:
        st.error(
            "🚫 A completed viva is already on record for this Roll Number "
            "on this link. If this is a mistake, contact your faculty."
        )

    st.divider()
    st.subheader("🔑 Your Gemini API Key")
    st.caption(
        "Each student uses their OWN free key — this keeps your viva from "
        "ever being slowed down by other students. Get one in under a "
        "minute at [aistudio.google.com/apikey](https://aistudio.google.com/apikey) "
        "(sign in with any Google account, click \"Create API key\"). It is "
        "never saved anywhere — not in the scoresheet, not in Google Sheets."
    )
    st.text_input(
        "Gemini API Key", type="password", placeholder="AIza...",
        key="gemini_api_key",
    )

    st.divider()
    st.subheader("📄 Upload Project")
    uploaded_file = st.file_uploader(
        "Upload your project report",
        type=["pdf", "docx"],
        help="Questions will be based entirely on your project"
    )

    start_btn = st.button(
        "🎓 Start Viva", type="primary",
        disabled=(uploaded_file is None or not student_name or not student_roll
                  or already_done or not (st.session_state.get("gemini_api_key") or "").strip())
    )
    if not st.session_state.get("gemini_api_key", "").strip():
        st.warning("Enter your Gemini API key to begin.")
    if not student_name:
        st.warning("Enter student name to begin.")
    elif not student_roll:
        st.warning("Enter roll number to begin.")
    elif already_done:
        pass  # the error above already explains why the button is disabled
    elif uploaded_file is None:
        st.warning("Upload project to begin.")

# --- Session state init ---
for key, default in [
    ("messages", []),
    ("viva_started", False),
    ("exchange_count", 0),
    ("project_text", ""),
    ("viva_ended", False),
    ("score_saved", False),
    ("final_score", None),
    ("excel_row_num", None),
    ("final_grade", ""),
    ("project_name", ""),
    ("closing_message", ""),
    ("saved_path", ""),
    ("cheated_detected", False),
    ("timeout_triggered", False),
    ("viva_start_time", None),
    ("gemini_working_model", None),
]:
    if key not in st.session_state:
        st.session_state[key] = default

# --- Active Focus & Timer Monitor (Sidebar Injection) ---
if st.session_state.viva_started and not st.session_state.viva_ended and VIVA_TIME_LIMIT_MINUTES > 0:
    elapsed = int(time.time() - st.session_state.viva_start_time)
    remaining_seconds = max(0, VIVA_TIME_LIMIT_MINUTES * 60 - elapsed)
    
    with st.sidebar:
        st.divider()
        # Render the controller iframe
        viva_signal = render_viva_controller(remaining_seconds)
        
        # Monitor signals returned from client-side JS
        if viva_signal == "cheated":
            st.session_state.cheated_detected = True
            st.session_state.viva_ended = True
            st.rerun()
        elif viva_signal == "timeout" or remaining_seconds <= 0:
            st.session_state.timeout_triggered = True
            st.session_state.viva_ended = True
            st.rerun()

# --- Start viva ---
if (start_btn and not st.session_state.viva_started and uploaded_file
        and student_name and student_roll and not already_done):
    st.session_state.project_name = uploaded_file.name
    with st.spinner("📖 Reading your project..."):
        project_text = extract_text(uploaded_file)
        st.session_state.project_text = project_text

    st.session_state.viva_start_time = time.time()

    # Precomputed as plain strings (rather than nested f-string expressions)
    # to keep the big SYSTEM_PROMPT f-string below readable.
    mandatory_questions_block = ""
    if VIVA_MANDATORY_QUESTIONS:
        numbered = "\n".join(
            f"{i + 1}. {q}" for i, q in enumerate(VIVA_MANDATORY_QUESTIONS)
        )
        mandatory_questions_block = (
            "\nSUBJECT-SPECIFIC QUESTIONS TO INCLUDE:\n"
            "You MUST ask each of the following questions at some point during "
            "this viva (you may phrase them more naturally in your own voice, "
            "but keep their meaning intact). Treat each one as ONE of your "
            "one-question-at-a-time turns, spread out among the project-"
            "specific questions rather than asked back-to-back:\n"
            f"{numbered}\n"
        )

    SYSTEM_PROMPT = f"""You are a strict but fair oral viva examiner for a PGDM {subject} course at Great Lakes Institute of Management.

Student name: {student_name}
Roll No: {student_roll}
Difficulty level: {difficulty}
{f'''
ADDITIONAL FACULTY INSTRUCTIONS — follow these when choosing and phrasing
questions, in addition to (not instead of) the rules below:
{VIVA_CUSTOM_INSTRUCTIONS.strip()}
''' if VIVA_CUSTOM_INSTRUCTIONS.strip() else ""}
{mandatory_questions_block}
The student has submitted the following project. Base ALL your questions ONLY on this project:

--- PROJECT START ---
{truncate(project_text)}
--- PROJECT END ---

CRITICAL FORMATTING RULE — READ CAREFULLY:
- Every reply you send must contain EXACTLY ONE question, and nothing more.
- Never number or list multiple questions ("1)... 2)..."). Never use "also",
  "additionally", "and also tell me", or similar to tack a second question
  onto the same reply.
- Your reply should contain AT MOST ONE question mark ("?"). If you notice
  you have written more than one question, delete every question except the
  first before sending your reply.
- If you want to test the student on several concepts, ask about only ONE of
  them now. Wait for their answer. You will get another turn to ask about the
  next one — do not rush multiple concepts into a single message.

Your rules:
- Ask ONE question at a time (see CRITICAL FORMATTING RULE above — this is
  the most important rule in this prompt).
- Keep responses concise — this is a spoken oral viva.
- Focus on the following two-phase examination flow:

  PHASE 1: CONCEPT AUTHENTICATION (First 2-3 questions)
  Your FIRST job is to authenticate the student: confirm they genuinely know the
  concepts, theories, models, frameworks and terminology that appear in THEIR OWN
  report. Identify the key concepts actually named in the project text above and
  test the student on them, ONE CONCEPT PER TURN.
  - Pick ONE specific term/model/framework that appears in the report and ask the
    student to DEFINE it in their own words. Do this in a single, focused question.
  - On a LATER turn, ask how that specific concept was applied in their project
    and why they chose it — as its own separate question, not combined with the
    definition question.
  - Across several separate turns (not one combined message), cover AT LEAST TWO
    DIFFERENT concepts from their report before you move on to Phase 2. "Cover"
    means you asked about it — it does NOT mean the student has to answer it
    correctly before you're allowed to move on (see the strict repeat limit
    below for why).
  - STRICT LIMIT ON REPEATS — this matters as much as the one-question rule:
    if a student's answer on a concept is wrong, vague, or garbled, you may
    ask AT MOST ONE follow-up attempt on that SAME concept (e.g. a simpler
    rephrasing, or narrowing to just one part of it). If that second attempt
    is STILL unsatisfactory, do NOT ask about that concept again in any form
    — never a third rephrasing. Silently note the gap for your final
    assessment, weight the score down for it, and move on to a genuinely
    DIFFERENT concept or straight to Phase 2. Two total attempts per concept
    is the hard ceiling, no exceptions, even if the student's answer still
    seems weak — the viva must keep moving forward.
  - If the student cannot define or explain the core concepts written in their own
    report even after that one retry, treat this as a red flag for authenticity,
    note it explicitly, and weight the final score down accordingly — but do
    this by moving on and reflecting it in your assessment, not by dwelling on
    the same concept further.

  PHASE 2: PROJECT DEEP DIVE (Remaining questions — this is MOST of the viva)
  Once the concept authentication is done (after at most ~4 exchanges), this
  phase should fill essentially all of the questions remaining out of
  {VIVA_TOTAL_QUESTIONS} — do not treat concept authentication as "most of"
  the viva. Probe their specific methodology, findings, data collection, and
  recommendations, ONE DISTINCT ANGLE PER QUESTION — e.g. one question on why
  they chose their methodology, a separate later question challenging a
  specific data point or assumption, another on an alternative they didn't
  consider, another on a limitation, another on how a recommendation would
  actually be implemented. Never repeat the same angle twice.
  - Challenge weak arguments, assumptions, or inconsistencies in their data.
  - Check their knowledge of their own analysis.

- NEVER REPEAT A QUESTION, AT ANY POINT IN THE VIVA — this rule applies to
  the ENTIRE conversation so far, not just your last few turns. Before you
  write your next question, scroll back through EVERY question you have
  already asked in this conversation (Phase 1 and Phase 2 alike, including
  ones from many exchanges ago) and confirm your new question is not the
  same one, and not just a reworded version of the same fact or figure you
  already asked about. This check matters MOST in the final couple of
  exchanges, when it is tempting to reach back to something asked earlier
  simply because fresh material feels scarce — do not do this. If you
  genuinely cannot find a new angle on the project itself, ask about a
  smaller sub-point you have not yet touched (a specific number, a specific
  sentence, a specific chart or table in the report, an implication of an
  answer they already gave), or pose a hypothetical/what-if variation on the
  project — but never ask something you have already asked, word-for-word
  or in substance, in this same viva.
- After every 5 exchanges give a brief mid-viva remark (one or two sentences),
  then still ask only ONE question in that same reply — the remark does not
  give you license to ask more than one question.
- DO NOT END EARLY: never output "VIVA COMPLETE" before you have asked
  EXACTLY {VIVA_TOTAL_QUESTIONS} questions, even if Phase 1 went smoothly and
  you feel you've "covered enough." Reaching {VIVA_TOTAL_QUESTIONS} exchanges
  is a hard floor, not a suggestion — if you run out of fresh Phase 2 angles,
  find another distinct one (a different section, metric, or assumption in
  the report) rather than wrapping up early or reusing an earlier question.
  Ending before {VIVA_TOTAL_QUESTIONS} questions is a failure to follow this
  prompt, and so is repeating a question to fill time.
- After {VIVA_TOTAL_QUESTIONS} exchanges (not before), end the viva with EXACTLY this format:

VIVA COMPLETE
Score: X/{VIVA_MAX_SCORE}
Strengths: [2-3 specific points]
Areas for Improvement: [2-3 specific points]
Recommended Topics: [list]

The "Score: X/{VIVA_MAX_SCORE}" line is MANDATORY and must contain an actual
number, not the literal letter X — replace X with your real numeric mark
from 0 to {VIVA_MAX_SCORE} (whole or half-point, e.g. "Score: 11/{VIVA_MAX_SCORE}"
or "Score: 11.5/{VIVA_MAX_SCORE}"). Never omit this line, never leave it as
a word or a range instead of one number, and never put the score anywhere
else in the message — it must appear on its own "Score: " line in exactly
this closing block.

Begin now by greeting {student_name} warmly and starting Phase 1 (Concept Authentication) by asking your first question about a key concept in their project report."""

    st.session_state.messages = [{"role": "system", "content": SYSTEM_PROMPT}]

    with st.spinner("Examiner is preparing..."):
        reply = chat_with_llm(st.session_state.messages)

    if reply is None:
        # chat_with_llm already showed the error. Leave viva_started False so
        # the student just sees the Start button again and can retry.
        st.stop()

    st.session_state.messages.append({"role": "assistant", "content": reply})
    st.session_state.viva_started = True

# --- Project preview in sidebar ---
if st.session_state.project_text:
    with st.sidebar:
        st.divider()
        st.caption(f"📋 {st.session_state.project_name}")
        st.caption(f"{len(st.session_state.project_text):,} characters loaded")
        with st.expander("Preview"):
            st.write(st.session_state.project_text[:400] + "...")

# --- Display chat ---
for msg in st.session_state.messages:
    if msg["role"] == "system":
        continue
    with st.chat_message("assistant" if msg["role"] == "assistant" else "user"):
        st.markdown(msg["content"])

# --- Request a final summary from the LLM (used when the exchange cap is hit
#     but the model hasn't produced the VIVA COMPLETE block yet). ---
def request_final_summary():
    closing_user_turn = (
        "The viva is now complete. Please immediately produce the final assessment "
        "in EXACTLY this format, with no preamble or follow-up questions:\n\n"
        "VIVA COMPLETE\n"
        f"Score: X/{VIVA_MAX_SCORE}\n"
        "Strengths: [2-3 specific points based on the student's actual answers]\n"
        "Areas for Improvement: [2-3 specific points]\n"
        "Recommended Topics: [list]\n\n"
        f"The 'Score: X/{VIVA_MAX_SCORE}' line is MANDATORY — replace X with an actual "
        f"number from 0 to {VIVA_MAX_SCORE} (whole or half-point, e.g. "
        f"'Score: 11/{VIVA_MAX_SCORE}' or 'Score: 11.5/{VIVA_MAX_SCORE}'). Do not leave X "
        "as a literal letter, a word, or a range — it must be one specific "
        "number, on its own line."
    )
    st.session_state.messages.append({"role": "user", "content": closing_user_turn})
    summary = chat_with_llm(st.session_state.messages)
    if summary is None:
        # Roll back the closing nudge so a retry starts from a clean state
        # instead of stacking up duplicate "wrap up now" turns.
        st.session_state.messages.pop()
        st.stop()
    st.session_state.messages.append({"role": "assistant", "content": summary})
    return summary

# --- Narrow follow-up used ONLY when a closing message already contained
#     "VIVA COMPLETE" but no parseable numeric score (a malformed or missing
#     Score line) — asks for nothing but the number, one more time, before
#     falling back to the manual-entry UI. Returns a float or None. ---
def request_score_only():
    nudge = (
        f"Your previous message was missing a valid numeric score. Reply with "
        f"ONLY one line and nothing else — no words, no explanation, no "
        f"repeated assessment:\n\nScore: X/{VIVA_MAX_SCORE}\n\nReplace X with your "
        f"real numeric mark for this student, from 0 to {VIVA_MAX_SCORE} "
        f"(whole or half-point, e.g. 'Score: 11/{VIVA_MAX_SCORE}')."
    )
    st.session_state.messages.append({"role": "user", "content": nudge})
    reply = chat_with_llm(st.session_state.messages)
    if reply is None:
        st.session_state.messages.pop()
        return None
    st.session_state.messages.append({"role": "assistant", "content": reply})
    return parse_score(reply)

def resolve_final_score(final_text):
    """Parse the score out of the closing message, and if that fails, make
    ONE narrow follow-up attempt asking the model for just the number before
    giving up (the manual-entry UI is still the ultimate fallback)."""
    score = parse_score(final_text)
    if score is None:
        with st.spinner("Score was missing — asking the examiner once more..."):
            score = request_score_only()
    return score

# --- Handle student response ---
def handle_response(user_text):
    st.session_state.messages.append({"role": "user", "content": user_text})
    st.session_state.exchange_count += 1

    with st.chat_message("user"):
        st.markdown(user_text)

    with st.chat_message("assistant"):
        with st.spinner("Examiner is responding..."):
            reply = chat_with_llm(st.session_state.messages)
        if reply is None:
            # Roll back this turn so the student's exchange count and chat
            # history look exactly as if they hadn't submitted yet — they
            # can just answer again once the API is free.
            st.session_state.messages.pop()
            st.session_state.exchange_count -= 1
            st.stop()
        st.session_state.messages.append({"role": "assistant", "content": reply})
        st.markdown(reply)

    st.sidebar.metric("Exchanges", st.session_state.exchange_count)

    should_end = ("VIVA COMPLETE" in reply) or (st.session_state.exchange_count >= VIVA_TOTAL_QUESTIONS)
    if should_end:
        final_text = reply
        if "VIVA COMPLETE" not in reply:
            with st.chat_message("assistant"):
                with st.spinner("📋 Preparing final assessment..."):
                    final_text = request_final_summary()
                st.markdown(final_text)

        st.session_state.viva_ended = True
        st.session_state.final_score = resolve_final_score(final_text)
        st.session_state.final_grade = get_grade(st.session_state.final_score)
        st.session_state.closing_message = final_text

# --- Input area (text only) ---
if st.session_state.viva_started and not st.session_state.viva_ended:
    typed = st.chat_input("Type your answer here...")
    if typed:
        handle_response(typed)

# --- Handle termination cases ---
if st.session_state.viva_ended:
    if st.session_state.get("cheated_detected", False) and not st.session_state.score_saved:
        st.session_state.final_score = 0.0
        st.session_state.final_grade = "F (Academic Dishonesty)"
        st.session_state.closing_message = "VIVA TERMINATED: Student switched tabs or minimized the exam window."
        
    elif st.session_state.get("timeout_triggered", False) and not st.session_state.score_saved:
        with st.spinner("⏳ Time's up! Generating final assessment..."):
            final_text = request_final_summary()
        st.session_state.final_score = resolve_final_score(final_text)
        st.session_state.final_grade = get_grade(st.session_state.final_score)
        st.session_state.closing_message = final_text

# --- Viva ended screen and saving ---
if st.session_state.viva_ended:
    st.divider()
    if st.session_state.get("cheated_detected", False):
        st.error("🚨 VIVA TERMINATED: Tab switching or window minimization detected. This incident has been logged.")
    elif st.session_state.get("timeout_triggered", False):
        st.warning("⏱️ Time limit reached! The viva has been automatically submitted.")
    else:
        st.subheader("🏁 Viva Complete")

    # ---- AUTO-SAVE the scoresheet immediately ----
    if not st.session_state.score_saved:
        closing = st.session_state.closing_message or (
            st.session_state.messages[-1]["content"] if st.session_state.messages else ""
        )
        strengths, improvements = parse_feedback(closing)
        
        # Override values if cheated
        if st.session_state.get("cheated_detected", False):
            strengths = "N/A - Terminated for cheating"
            improvements = "Switched tabs or minimized browser tab during active exam"
            
        try:
            filepath, excel_row = save_to_excel(
                student_name=student_name,
                student_roll=student_roll,
                student_email=student_email,
                subject=subject,
                difficulty=difficulty,
                score=st.session_state.final_score,
                grade=st.session_state.final_grade,
                strengths=strengths,
                improvements=improvements,
                exchanges=st.session_state.exchange_count,
                project_name=st.session_state.project_name,
            )
            st.session_state.score_saved = True
            st.session_state.saved_path = filepath
            # Remembered so a later manual score override (see below) updates
            # this same row instead of appending a duplicate one.
            st.session_state.excel_row_num = excel_row
            st.success(f"✅ Scoresheet auto-saved locally to:\n`{filepath}`")
        except Exception as e:
            st.error(f"⚠️ Local auto-save failed: {e}")

        # Post to Google Sheets if webhook is configured. The result is
        # stored (not just shown once) so it's still visible on every later
        # rerun of this screen — see the persistent display block below.
        gs_success, gs_message = save_to_google_sheets(
            student_name=student_name,
            student_roll=student_roll,
            student_email=student_email,
            subject=subject,
            difficulty=difficulty,
            score=st.session_state.final_score,
            grade=st.session_state.final_grade,
            strengths=strengths,
            improvements=improvements,
            exchanges=st.session_state.exchange_count,
            project_name=st.session_state.project_name,
        )
        st.session_state.gs_save_result = (gs_success, gs_message)

    # ---- Persistent Google Sheets status (survives later reruns) ----
    if st.session_state.get("gs_save_result"):
        gs_success, gs_message = st.session_state.gs_save_result
        if gs_success:
            st.success(gs_message)
        else:
            st.error(gs_message)

    # ---- Score / grade display ----
    col1, col2 = st.columns(2)
    with col1:
        if st.session_state.final_score is not None:
            st.metric("Final Score", f"{st.session_state.final_score}/{VIVA_MAX_SCORE}")
        else:
            st.metric("Final Score", "—")
    with col2:
        st.metric("Grade", st.session_state.final_grade)

    # ---- Manual override if the LLM still didn't give a numeric score ----
    if st.session_state.final_score is None:
        st.warning("The examiner did not return a numeric score. You can set one manually below.")
        manual = st.number_input(
            f"Manual final score (0-{VIVA_MAX_SCORE})", min_value=0.0, max_value=float(VIVA_MAX_SCORE),
            step=0.5, value=float(VIVA_MAX_SCORE) / 2, key="manual_score"
        )
        if st.button("Apply manual score and re-save"):
            st.session_state.final_score = float(manual)
            st.session_state.final_grade = get_grade(st.session_state.final_score)
            closing = st.session_state.closing_message or ""
            strengths, improvements = parse_feedback(closing)
            
            if st.session_state.get("cheated_detected", False):
                strengths = "N/A - Terminated for cheating"
                improvements = "Switched tabs or minimized browser tab during active exam"
                
            filepath, excel_row = save_to_excel(
                student_name=student_name, student_roll=student_roll, student_email=student_email,
                subject=subject, difficulty=difficulty,
                score=st.session_state.final_score, grade=st.session_state.final_grade,
                strengths=strengths, improvements=improvements,
                exchanges=st.session_state.exchange_count,
                project_name=st.session_state.project_name,
                # Overwrite the "Pending" row the auto-save already wrote,
                # instead of appending a second row for the same student.
                row_num=st.session_state.get("excel_row_num"),
            )
            st.session_state.saved_path = filepath
            st.session_state.excel_row_num = excel_row
            st.success(f"✅ Updated and saved to `{filepath}`")

            # Post manual override to Google Sheets
            gs_success, gs_message = save_to_google_sheets(
                student_name=student_name,
                student_roll=student_roll,
                student_email=student_email,
                subject=subject,
                difficulty=difficulty,
                score=st.session_state.final_score,
                grade=st.session_state.final_grade,
                strengths=strengths,
                improvements=improvements,
                exchanges=st.session_state.exchange_count,
                project_name=st.session_state.project_name,
            )
            st.session_state.gs_save_result = (gs_success, gs_message)
            st.rerun()

    # ---- Download button kept as a BACKUP per your request ----
    if st.session_state.score_saved and os.path.exists(SCORESHEET_FILE):
        with open(SCORESHEET_FILE, "rb") as f:
            st.download_button(
                label="⬇️ Download Scoresheet (backup copy)",
                data=f,
                file_name="GLIM_Viva_Scores.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
        st.caption(f"Master file on disk: `{st.session_state.saved_path or SCORESHEET_FILE}`")

elif not st.session_state.viva_started:
    st.info("👈 Fill in settings and upload project to begin.")
